version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: elixir:1.6
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
