#!/bin/sh

# Produce release and run it
# Runs on localhost:3000
# Should be run from the root directory.

set -ev
set -o posix

export ERTS_LIB_DIR="#{locate erts-9.2/lib | head -1}"
export HOST=localhost
export PORT=3000
export MIX_ENV=prod
export REL_ROOT=./_build/prod/rel/bs
export REPLACE_OS_VARS=1
export VERBOSE=1

[[ ! ($SKIP_ASSETS && ${SKIP_ASSETS-x}) ]] && \
	sh -c "cd assets && yarn && NODE_ENV=production ./node_modules/.bin/webpack -p" && \
	mix phx.digest

mix release --verbose --dev && $REL_ROOT/bin/bs foreground
